### PR TITLE
Fix typos in Readme and format ThresholdKey.java

### PR DESCRIPTION
**Pull request by bigman212**
Only formatting and typos are fixed. UI tests are all green.

### CODE REVIEW

**Comment by bigman212** [comment]
@metalurgical @metallicalfa2

**Review by metalurgical — APPROVED** [review]
LGTM

**Comment by bigman212** [comment]
@metalurgical feel free to merge, I don't have permissions to merge

**Comment by metalurgical** [comment]
@bigman212 Thanks for your contribution 👍🏻

**Pull request merged**
